CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
MIN_SENTENCE_LENGTH = 3
MAX_FRAGMENT_LENGTH = 100
INPUT_FILE = 'files/transcript.txt'
CLEANED_FILE = 'files/transcript_preprocessed.txt'
PROCESSED_FILE = 'files/transcript_processed.txt'
OUTPUT_FILE = 'files/transcript_formatted.txt'
API_URL = "http://0.0.0.0:5000/v1/completions"
API_TIMEOUT = 60
MAX_TOKENS = 150
STOP_SEQUENCES = ["\n\n", "###", "##"]
SPEAKER_FORMAT = "{name}: {content}"
REPETITION_PENALTY = 1.2
TEMPERATURE = 0.7
TOP_P = 0.9
MAX_SENTENCE_VALIDATION_ERRORS = 5
LOG_DIR = 'logs'
LOG_FILE = 'runlog.log'

__all__ = [
    'CHUNK_SIZE', 'CHUNK_OVERLAP', 'API_URL', 'API_TIMEOUT',
    'MAX_TOKENS', 'STOP_SEQUENCES', 'REPETITION_PENALTY',
    'TEMPERATURE', 'TOP_P', 'MIN_SENTENCE_LENGTH',
    'MAX_FRAGMENT_LENGTH', 'SPEAKER_FORMAT',
    'MAX_SENTENCE_VALIDATION_ERRORS', 'INPUT_FILE', 'OUTPUT_FILE',
    'LOG_DIR', 'LOG_FILE'
]