base_model: /media/external_drive1/ai/textdata/models/TinyLlama-1.1B-Chat-v1.0
model_config_type: llama
tokenizer_type: AutoTokenizer
trust_remote_code: true

# Quantization
load_in_4bit: true
use_qlora: true
adapter: qlora
lora_r: 8  # <<< MUST ADD THIS (typical values: 8, 16, 32, 64)
lora_alpha: 16  # <<< MUST ADD THIS (typically 2x lora_r)
lora_target_modules: "all-linear"  # or specific modules like ["q_proj", "v_proj"]
lora_dropout: 0.05
bnb_4bit_compute_dtype: float16
bnb_4bit_quant_type: nf4
bnb_4bit_use_double_quant: true
torch_dtype: float16

# Dataset and training settings remain the same as before
datasets:
  - path: /home/kdog/text-generation-webui/training/datasets/augmented_dataset.jsonl
    type: alpaca
    dataset_prepared_path: /home/kdog/text-generation-webui/training/datasets/prepared
    field_mapping:
      instruction: "instruction"
      input: "input"
      output: "output"

output_dir: /home/kdog/text-generation-webui/training/trained_checkpoints/tinyllama_punctuation
num_epochs: 5
learning_rate: 1e-5
lr_scheduler: cosine
warmup_steps: 50
optimizer: adamw_torch
weight_decay: 0.01

# Memory settings
sequence_len: 300
micro_batch_size: 1
gradient_accumulation_steps: 4
gradient_checkpointing: true
train_on_inputs: false
add_eos_token: true

# Other settings
bf16: false
fp16: true
logging_steps: 10
save_strategy: steps
save_steps: 200
save_total_limit: 2
eval_steps: 200
eval_strategy: steps
preprocessing_num_workers: 4
dataloader_num_workers: 2
group_by_length: true